name = "statics"
main = "src/index.js"
compatibility_date = "2024-12-02"

# Environment variables
[vars]
#DROGUIER_VAR_NAME = "your-secret-key-here-change-in-production"
DROGUIER_VAR_NAME = "your-secret-key"

# KV Namespace binding for storing bookmarks
[[kv_namespaces]]
binding = "STORAGE_KV"
id = "564e8a6653a546f2b4ce048b126b9756"
preview_id = "7ff1ac8a7d9744e8b93cbcd6c0c45c74"

[[d1_databases]]
binding = "datastoraged01"
database_name = "datastoraged01"
database_id = "266bdca3-6cf1-4e63-852f-52831b38e07b"
