name = "cloudflare-api-bookmarks"
main = "src/index.js"
compatibility_date = "2024-01-01"

# KV Namespace binding for storing bookmarks
[[kv_namespaces]]
binding = "BOOKMARKS_KV"
id = "droguier-bookmark-kv"
preview_id = "droguier-kv"
